[#87} refactor support file types
rokwire/content-building-block pull request #88
Opened 2023-09-29 14:30 UTC by bsdworkin

## Description
_Please provide a summary of the pull request and the issue it resolves. Please add necessary details, context, dependencies, explanation of when review is needed (see next section), etc._

**Resolves #87**

[comment]: # (This project only accepts pull requests related to open issues.)
[comment]: # (If suggesting a new feature or change, please discuss it in an issue first.)
[comment]: # (If fixing a bug, there should be an issue describing it with steps to reproduce.)

## Review Time Estimate
_Please give your idea of how soon this pull request needs to be reviewed by selecting one of the options below. This can be based on the criticality of the issue at hand and/or other relevant factors._

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Immediately
- [ ] Within a week
- [x] When possible

## Type of changes
_Please select a relevant option:_

[comment]: # (To select an option, please put an 'x' in the applicable box.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Other (any another change that does not fall in one of the above categories.)

## Checklist:
_Please select all applicable options:_

[comment]: # (To select your options, please put an 'x' in the all boxes that apply.)
[comment]: # (If you're unsure about any of these, don't hesitate to ask. We're here to help!.)

- [x] I have signed the Rokwire Contributor License Agreement ([CLA](https://rokwire.org/rokwire_cla)). (_Any contributor who is not an employee of the University of Illinois whose official duties include contributing to the Rokwire software, or who is not paid by the Rokwire project, needs to sign the CLA before their contribution can be accepted._)
- [x] I have updated the [CHANGELOG](../CHANGELOG.md).
- [x] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] My change requires updating the documentation.
- [ ] I have made necessary changes to the documentation.
- [ ] I have added tests related to my changes.
- [x] My changes generate no new warnings.
- [x] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

---

[comment]: # (Template credit: This pull request template is based on Embedded Artistry {https://github.com/embeddedartistry/templates/blob/master/.github/PULL_REQUEST_TEMPLATE.md}, Clowder {https://github.com/clowder-framework/clowder/blob/develop/.github/PULL_REQUEST_TEMPLATE.md}, and TalAter {https://github.com/TalAter/open-source-templates} templates.)

2023-09-29 14:32 UTC, bsdworkin commented
@mdryankov no need for review here. Since you are the code owner you are automatically added to review

2023-09-29 14:33 UTC, bsdworkin commented
Last issue to fix: Decoding errors at client for files

2023-10-27 17:53 UTC, roberlander2 requested changes
Thanks @bsdworkin, I left some feedback below. The main issues I found are inconsistencies between the docs and some of the API handlers and some of the Mongo filters being used. I think there are also some category permissions checks missing.

2023-10-27 17:53 UTC, roberlander2 commented on core/services.go
> +	item, err := s.app.storage.CreateDataContentItem(item)
I think we should check the category permissions against the token permissions to make sure the user can create the content item.

2023-10-27 17:53 UTC, roberlander2 commented on core/services.go
> +	item, err := s.app.storage.UpdateCategory(&appID, orgID, item)
I think we should check the category permissions against the token permissions before creating, updating, or deleting the category.

2023-10-27 17:53 UTC, roberlander2 commented on core/services.go
> +	_, err := s.app.awsAdapter.UploadFile(file, path)
Let's check the category permissions against the token permissions before uploading.

2023-10-27 17:53 UTC, roberlander2 commented on core/services.go
> +	for _, element := range categoryItem.Permissions {
Let's turn this permissions check into a helper function since the same check is used multiple times.

2023-10-27 17:53 UTC, roberlander2 commented on driver/web/rest/adminapis.go
> +	err = json.Unmarshal(data, &item)
Let's use `json.NewDecoder(r.Body).Decode(&item)` wherever it's needed instead of reading and unmarshalling separately.

2023-10-27 17:53 UTC, roberlander2 commented on driver/web/rest/adminapis.go
> +	key := vars["id"]
We should not need to get the `id` here because this API just searches content items by category.

2023-10-27 17:53 UTC, roberlander2 commented on driver/web/rest/adminapis.go
> +	id := vars["id"]
This path parameter doesn't match up with the docs for this API and it isn't used except to log an error.

2023-10-27 17:53 UTC, roberlander2 commented on driver/web/rest/adminapis.go
> +	key := vars["id"]
Let's make the path parameter name match `key`.

2023-10-27 17:53 UTC, roberlander2 commented on driver/web/rest/adminapis.go
> +	id := vars["id"]
Let's make this path parameter `name` because that is what we are searching by in Mongo.

2023-10-27 17:53 UTC, roberlander2 commented on driver/web/rest/adminapis.go
> +	id := vars["id"]
Let's make this path parameter `name` because that is what we are searching by in Mongo.

2023-11-02 21:11 UTC, roberlander2 requested changes
Thanks @bsdworkin, this is getting very close. I left more comments below to fix a few small things.

2023-11-02 21:11 UTC, roberlander2 commented on driver/web/docs/resources/admin/data-content-items.yaml
> +      description: Success
The docs should show that you are returning the created content item in your handler.

2023-11-02 21:11 UTC, roberlander2 commented on driver/web/docs/resources/admin/data-content-items.yaml
> +      description: Success
The docs should show that you are returning the updated content item in your handler.

2023-11-06 22:05 UTC, roberlander2 submitted a review, later dismissed
Thanks @bsdworkin, this looks good to me. I just made one last commit to fix a few logging bugs that I found.

Hi @mdryankov, this PR is ready for your review when you are ready.

2024-01-25 04:47 UTC, shurwit approved these changes
Thanks @bsdworkin @roberlander2, I made some fixes to the issues I saw. Merging now.

2024-01-25 04:51 UTC, merged